name: build-release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Release name"
        required: true
        default: "manual-build"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          memcached \
          libmemcached-dev \
          libmariadb-dev \
          libmariadb3

    - name: Bootstrap
      run: ./config/bootstrap

    - name: Configure
      run: |
        ./configure \
          --with-mysql=/usr/bin/mariadb_config

    - name: Build
      run: make -j$(nproc)

    - name: Install to staging directory
      run: |
        make install DESTDIR=${{ github.workspace }}/release

    - name: Archive binary release
      run: |
        tarball="build-${{ github.event.inputs.release_name }}-${{ github.sha }}.tar.gz"
        echo "Creating archive $tarball"
        tar -czf "$tarball" -C release .
        echo "tarball=$tarball" >> $GITHUB_ENV # save for next step

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_name }}
        release_name: ${{ github.event.inputs.release_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.tarball }}
        asset_name: ${{ env.tarball }}
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}